ARG BASE_IMAGE="fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

RUN dnf install -y \
        systemd \
        sudo \
        git \
    && dnf clean all \
    && rm -rf /var/cache/yum

# fix for PAM/SSH
RUN chmod 0640 /etc/shadow

RUN useradd -l -u 1000 -G wheel -md /home/gbraad -s /bin/bash -p gbraad gbraad \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers 

USER gbraad

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ~/.dotfiles \
    && cd ~/.dotfiles \
    && sh ./install.sh

USER root

RUN chsh -s /usr/bin/zsh gbraad

# install tailscale
RUN dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale \
    && systemctl enable tailscaled

# Enable systemd
ENTRYPOINT [ "/sbin/init" ]
