ARG BASE_IMAGE="debian"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG USER="gbraad"
ARG HOMEBASE="/home"
ARG HOME="${HOMEBASE}/${USER}"

LABEL org.opencontainers.image.source = "https://github.com/gbraad-dotfiles/debian"

RUN apt-get update \
    && apt-get install -y \
        systemd \
	init \
        sudo \
        git \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -l -u 1000 -G sudo -md ${HOME} -p ${USER} ${USER} \
    && sed -i.bkp -e '/Defaults\tuse_pty/d' -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers

USER ${USER}

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ~/.dotfiles \
    && cd ~/.dotfiles \
    && bash ./install.sh

USER root

RUN chsh -s /bin/zsh ${USER}

# install tailscale
RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg -o /usr/share/keyrings/tailscale-archive-keyring.gpg \
    && curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list \
    && apt-get update \
    && apt-get install -y \
        tailscale \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale
# already 'enabled' by default
#   && systemctl enable tailscaled

# Enable systemd
ENTRYPOINT [ "/sbin/init" ]
