ARG BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/base"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

RUN dnf install -y \
        moby-engine \
        containerd \
    && dnf clean all \
    && rm -rf /var/cache/yum

